name: Deploy to 's0u7a.net' via Cloudflare Pages

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  Setup:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: npm i
  Build:
    needs: Setup
    runs-on: ubuntu-latest
    
    steps:
      - name: Build
        continue-on-error: true
        run: npm run build
      - name: show dir info
        run: |
          pwd
          ls

  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy dist --project-name=astro-s0u7adotnet
        
